# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-rdiscount}
  s.version = "1.0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wlodek Bzyl"]
  s.date = %q{2010-05-19}
  s.description = %q{Sinatra extension providing RDiscount templates for Sinatra application.}
  s.email = %q{matwb@univ.gda.pl}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "examples/app.rb",
     "examples/config.ru",
     "examples/mapp.rb",
     "examples/public/stylesheets/application.css",
     "examples/views/hello.rdiscount",
     "examples/views/hello2.rdiscount",
     "examples/views/layout2.rdiscount",
     "lib/sinatra/rdiscount.rb",
     "sinatra-rdiscount.gemspec",
     "test/sinatra_rdiscount_test.rb",
     "test/test_helper.rb",
     "test/views/hello.rdiscount",
     "test/views/layout2.rdiscount"
  ]
  s.homepage = %q{http://github.com/wbzyl/sinatra-rdiscount}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Sinatra extension providing RDiscount templates for Sinatra application.}
  s.test_files = [
    "test/sinatra_rdiscount_test.rb",
     "test/test_helper.rb",
     "examples/app.rb",
     "examples/mapp.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, ["~> 0.9"])
      s.add_runtime_dependency(%q<erubis>, [">= 2.6.5"])
      s.add_runtime_dependency(%q<rdiscount>, [">= 1.5.8"])
      s.add_development_dependency(%q<rack>, [">= 1.0.0"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.3"])
    else
      s.add_dependency(%q<sinatra>, ["~> 0.9"])
      s.add_dependency(%q<erubis>, [">= 2.6.5"])
      s.add_dependency(%q<rdiscount>, [">= 1.5.8"])
      s.add_dependency(%q<rack>, [">= 1.0.0"])
      s.add_dependency(%q<rack-test>, [">= 0.5.3"])
    end
  else
    s.add_dependency(%q<sinatra>, ["~> 0.9"])
    s.add_dependency(%q<erubis>, [">= 2.6.5"])
    s.add_dependency(%q<rdiscount>, [">= 1.5.8"])
    s.add_dependency(%q<rack>, [">= 1.0.0"])
    s.add_dependency(%q<rack-test>, [">= 0.5.3"])
  end
end

